### ISSUE TITLE
Missing famous-global.js

### ISSUE THREAD

**Issue by irwansyahwii** [thomasstreet/famous-angular-starter#13]
I can't find famous-global.js so when the index.html opend in a browser it will complaint because famo.us is not found.

**Comment by jeffscottward** [comment]
Same here

**Comment by irwansyahwii** [comment]
After searching in every corners I finally found it inside famous-angular-example-master's bower.json file. Just add this line into your bower.json:

"famous": "http://code.famo.us/famous/global/0.2.2/famous-global-0.2.2.tar.gz"

**Comment by zackbrown** [comment]
Fortunately the famous-global dependency should now be included out of the box with version 0.4.0+ when you perform a `bower install famous-angular`

**Comment by mab-u** [comment]
Now waiting for the [update](https://github.com/Famous/famous/releases/tag/0.3.0) to
"famous": "http://code.famo.us/famous/global/0.3.0/famous-global-0.3.0.tar.gz"
Exciting times.
