### ISSUE TITLE
Bower can't find Famous-Angular

### ISSUE THREAD

**Issue by jeffscottward** [thomasstreet/famous-angular-starter#14]
Failed to execute "git ls-remote --tags --heads git://github.com/Famous/famous-angular.git", exit code of #128

This is stopping all of bower from installing what is needed and there for is blocking everything.

**Comment by zackbrown** [comment]
Looks like this is most likely a bower config issue.  Based on [this thread](https://github.com/bower/bower/issues/689) you could try `git config --global url."https://".insteadOf git://`

Did you end up getting past this?
