### ISSUE TITLE
Do I need to install these?

### ISSUE THREAD

**Issue by LouisWayne** [thomasstreet/famous-angular-starter#20]
Hello, I am learning famo.us/angularJs.

Do I need to install these?:

<script src="bower_components/angular-animate/angular-animate.js"></script>

```
<script src="bower_components/angular-cookies/angular-cookies.js"></script>
<script src="bower_components/angular-touch/angular-touch.js"></script>
<script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
<script src="bower_components/angular-resource/angular-resource.js"></script>
<script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>
<script src="bower_components/angular-route/angular-route.js"></script>

<script src="bower_components/underscore/underscore.js"></script>
```

I downloaded famo.us/angular through bower, and the Angular version is 1.2.x, but angular-animate requires 1.3.x.  Also why do you have underscore.js?

**Comment by ArEnSc** [comment]
Yes you do, need to install those since you are using angular, those are libraries required to create an angular app. I am not sure if underscore is required, it is useful by its self though.
