### ISSUE TITLE
bower_components installed in wrong directory

### ISSUE THREAD

**Issue by bingomanatee** [thomasstreet/famous-angular-starter#7]
bower_components installed in root, not in app and were invisible to application. 

fair warning, my bower was slightly out of date when I did the bootup.

**Comment by theshapguy** [comment]
I have the save problem.. Any idea how to fix it?

**Comment by prescottprue** [comment]
This also became a problem for when I started using a service that has the root folder being called src. I just did a find in folder for whatever the folder it is going into (root in your case) with a backslash in front, so `/root`. Then did replace with `/newFolder` with newFolder obviously being what folder you actually want source.

I believe it mostly just changes the gulp files that do the bower placement task (which are all placed into the gulp file and referenced).

**Comment by zackbrown** [comment]
The config in this file https://github.com/thomasstreet/famous-angular-starter/blob/master/.bowerrc should instruct the latest version of bower to install in app/bower_components, provided that you call `bower install` from the root of the project, i.e. one directory above the `app` folder.
