### ISSUE TITLE
Is Jade a depenency?

### ISSUE THREAD

**Issue by bingomanatee** [thomasstreet/famous-angular-starter#8]
Many people (like me) hate Jade - not a great thing to have as a dependency. If there is a jade-less way to do this thing, either docs for doing a "Jadeectomy" or a jadeectomy would be preferred

**Comment by zackbrown** [comment]
It is not a hard dependency, though it does make attribute-heavy Famo.us/Angular HTML much easier to read IMO.  A jadeectomy is a fully reasonable option and will not cause any problems with the library (just use HTML.)
