### ISSUE TITLE
Error while serving with Gulp

### ISSUE THREAD

**Issue by theshapguy** [thomasstreet/famous-angular-starter#9]
``` javascript
2 errors
/Users/Shapath/Developer/AngularJS/Tut/app/scripts/main/main-ctrl.js: line 1, col 1, Use the function form of "use strict".
/Users/Shapath/Developer/AngularJS/Tut/app/scripts/main/main-ctrl.js: line 3, col 1, 'angular' is not defined.
```

I have edited nothing. All I did was 

> npm install 

to add dependencies..

**Comment by theshapguy** [comment]
All I get is a blank page, when I do [localhost] /jade I get a

> Cannot GET /jade/

error

**Comment by surfjedi** [comment]
try - http://localhost:9000/#/jade, its got to with the way routes work in angular

**Comment by surfjedi** [comment]
Did you do bower install too?
